.\"                                      Hey, EMACS: -*- nroff -*-
.TH VUXCTL 1 "November 4, 2004" "0.4.9" "Vacillating Utilitarian eXtemporizer control"
.SH NAME
vuxctl \(en vux ogg/mp3 player control interface
.SH SYNOPSIS
.B vuxctl
.RI [\| "commands" \|]
.br
.SH DESCRIPTION
.PP
\fBvuxctl\fP is a control interface to the \fBvux\fP program.  It
provides greater control than the two signals provided by \fBvux\fP
itself.
See \fBvux(1)\fP for details.
.SH COMMANDS
Most commands are mutually exclusive with other commands.  When given on
the same command line, only the last of these commands will be honored.
\fBvuxctl\fP with no arguments is equivalent to \fBvuxctl help\fP.
.TP
.B "start"
Invokes \fBvux -x play\fP in the background if no playing \fBvux\fP
exists.  This command causes all other commands given on the same line
to be ignored.
.TP
.B "clean"
Removes possibly stale files in the vux directory that would prevent vux
from running.  Files removed are the vuxctl socket and any lockfiles.
By default, these are: \fB.vux/ctl\fP, \fB.vux/vux.pid\fP,
\fB.vux/scorelist.lock\fP, \fB.vux/agelist.lock\fP and
\fB.vux/countlist.lock\fP.
.TP
.B "double"
Double the rating multiplier for current song.  Mutually exclusive with
\fBhalf\fP.
.TP
.B "half"
Halve the rating multiplier for current song.  Since the rating
multiplier is an integer, halving the initial rating multiplier of 1 has
no effect.  Mutually exclusive with \fBdouble\fP.  
.TP
.B "up"
Increase the rating of the current song using the current rating
increase method.  Mutually exclusive with \fBdown\fP and \fInumber\fP.
.TP
.B "down"
Decrease the rating of the current song using the current rating
decrease method.  Mutually exclusive with \fBup\fP and \fInumber\fP.
.TP
.I "number"
Change the rating of the current song to \fInumber\fP.  Mutually
exclusive with \fBup\fP and \fBdown\fP.
.TP
.B "next"
Proceed to next song.  This does not effect current rating unless
\fBup\fP, \fBdown\fP or \fInumber\fP is also given.  Mutually exclusive
with \fBprevious\fP, \fBforward\fP and \fBreplay\fP.
.TP
.B "previous"
Proceed to previous song.  This does not effect current rating unless
\fBup\fP, \fBdown\fP or \fInumber\fP is also given.  If no previous song
exists, \fBprevious\fP acts as \fBreplay\fP.  Mutually exclusive with
\fBnext\fP, \fBforward\fP and \fBreplay\fP.
.TP
.B "forward"
Proceed to next random song, ignoring history.  This does not effect
current rating unless \fBup\fP, \fBdown\fP or \fInumber\fP is also
given.  Mutually exclusive with \fBnext\fP, \fBprevious\fP and
\fBreplay\fP.
.TP
.B "replay"
Replay current song.  This does not effect current rating unless
\fBup\fP, \fBdown\fP or \fInumber\fP is also given.  Mutually exclusive
with \fBnext\fP, \fBprevious\fP and \fBforward\fP.
.TP
.B "pause"
Pause or resume running ogg or mp3 player and its child.  This will only
work as a toggle if ps supports the \fB-o\fP option (ps from procps in
Debian does.)  Mutually exclusive with \fBresume\fP, \fBstop\fP,
\fBreload\fP, \fBsave\fP, \fBafter\fP and \fBhistory\fP.
.TP
.B "resume"
Resume running ogg or mp3 player and its child.  Mutually exclusive with
\fBpause\fP, \fBstop\fP, \fBreload\fP, \fBsave\fP, \fBafter\fP and
\fBhistory\fP.
.TP
.B "stop"
Quit \fBvux\fP.  Mutually exclusive with \fBpause\fP, \fBresume\fP,
\fBreload\fP, \fBsave\fP, \fBafter\fP and \fBhistory\fP.
.TP
.B "after"
Quit \fBvux\fP after the current playing song is finished.  Mutually
exclusive with \fBpause\fP, \fBstop\fP, \fBresume\fP, \fBreload\fP,
\fBsave\fP and \fBhistory\fP.
.TP
.B "reload"
Reload scorelist.  Mutually exclusive with \fBpause\fP, \fBresume\fP,
\fBstop\fP, \fBsave\fP, \fBafter\fP and \fBhistory\fP.
.TP
.B "save"
Save scorelist.  Mutually exclusive with \fBpause\fP, \fBresume\fP,
\fBstop\fP, \fBreload\fP, \fBafter\fP and \fBhistory\fP.
.TP
.B "history"
Show previous/next history of songs.  As stated above, output is
generated by \fBvux\fP.  Mutually exclusive with \fBpause\fP,
\fBresume\fP, \fBstop\fP, \fBreload\fP, \fBafter\fP and \fBsave\fP.
.TP
.B "help"
Show summary of options.  As stated above, output is generated by
\fBvux\fP.  This command causes all other commands given on the same
line to be ignored.
.SH DIAGNOSTICS
\fPvuxctl\fP will exit 0 if there are no errors.  Otherwise, the
following exit codes are used:
.TP
.B 1
Command failed.
.TP
.B 2
Start command was given, but vux.pid already exists.
.TP
.B 3
Command given, but no vux.pid exists.
.SH EXAMPLES
.TP
.B vuxctl next
Proceed to the next song without changing the rating of the current
song.
.TP
.B vuxctl up next
Increase the rating of the current song and proceed to the next song.
.TP
.B vuxctl 50
Set the rating of the current song to 50.
.TP
.B vuxctl replay
Replay current song.
.TP
.B vuxctl previous
Proceed to the previous song without changing the rating of the current
song.
.TP
.B vuxctl up previous
Increase the rating of the current song and proceed to the previous
song.
.TP
.B vuxctl double up next
Increase the rating of the current song by twice the usual amount and
proceed to the next song.
.TP
.B vuxctl double down
Decrease the rating of the current song by twice the usual amount but
continue playing it.
.TP
.B vuxctl double
Double the rating multiplier, affecting the rating change when the song
is skipped or played fully.
.SH BUGS
Use the Debian Bug Tracking System for reporting bugs and making
suggestions.
.SH SEE ALSO
.B vux(1)
.SH FILES
.TP
/etc/vuxrc
system configuration file
.TP
$HOME/.vux/vuxrc
user configuration file
.TP
$HOME/.vux/scorelist
default scorelist
.TP
$HOME/.vux/*.bak
default backup file; made before saving
.TP
$HOME/.vux/*.lock
default lockfile preventing a file save or load while saving
.TP
$HOME/.vux/vux.pid
file containing PID of any vux process using \-x play
.TP
$HOME/.vux/ctl
vux control socket
.SH AUTHOR
This manual page was written by Brian Nelson <bnelson@bloodclot.net>,
for the Debian GNU/Linux system (but may be used by others).
